[[examples]]
answers.p1 = '4,6,3,5,6,3,5,2,1,0'
input = '''
Register A: 729
Register B: 0
Register C: 0

Program: 0,1,5,4,3,0
'''

[[examples]]
answers.p2 = 117440
input = '''
Register A: 2024
Register B: 0
Register C: 0

Program: 0,3,5,4,3,0
'''

[real]
input = '''
Register A: 62769524
Register B: 0
Register C: 0

Program: 2,4,1,7,7,5,0,3,4,0,1,7,5,5,3,0'''
